### ISSUE TITLE
Wrong size for extra data

### ISSUE THREAD

**Issue by marcosps** [alexlarsson/skype-app#11]
Hi Alex,

when I try to install skype from flatpak, I see this problem:

marcos@xfiles:~$ sudo flatpak install --from https://s3.amazonaws.com/alexlarsson/skype-repo/skype.flatpakref
This application depends on runtimes from:
  http://sdk.gnome.org/repo/
Configure this as new remote 'gnome-1' [y/n]: y
Installing: com.skype.Client/x86_64/alpha
Updating: org.freedesktop.Platform/x86_64/1.4 from gnome
No updates.
Updating: org.freedesktop.Platform.Locale/x86_64/1.4 from gnome
No updates.
Installing: com.skype.Client/x86_64/alpha from com.skype.Client-origin

Downloading extra data 48,1 MB/48,1 MB                                                                                                  
error: Wrong size for extra data https://go.skype.com/skypeforlinux-64-alpha.deb

Let me know if you need more information!

**Comment by alexlarsson** [comment]
Should be fixed now.

**Comment by marcosps** [comment]
Worked, thanks!

**Comment by mrpdaemon** [comment]
Looks like there's another upstream release:

Updating: com.skype.Client/x86_64/alpha from com.skype.Client-1-origin
XA: Loading https://go.skype.com/skypeforlinux-64.deb using libsoup
XA: Received 53921360 bytes
Error: Failed to update com.skype.Client/x86_64/alpha: Wrong size for extra data https://go.skype.com/skypeforlinux-64.deb
error: One or more operations failed
