### ISSUE TITLE
Video call doesn't work

### ISSUE THREAD

**Issue by adityashah1212** [alexlarsson/skype-app#15]
In Skype beta one on one video call was enabled, rpm when installed works fine but flatpak skype video call button is grayed out

**Comment by erindru** [comment]
Im having the same issue - I wonder if its to do with allowing Flatpak access to the webcam device?

**Comment by alexlarsson** [comment]
Can you try `flatpak run --device=all com.skype.Client`
That will let it see your devices.

**Comment by adityashah1212** [comment]
Yup it works when access to devices is given

**Comment by alexlarsson** [comment]
@snaggen Maybe we should add this to the finish args
