### ISSUE TITLE
error: Wrong size for extra data https://go.skype.com/skypeforlinux-64.deb

### ISSUE THREAD

**Issue by enricotagliavini** [alexlarsson/skype-app#26]
Tried few minutes ago

```
$ flatpak install --from https://s3.amazonaws.com/alexlarsson/skype-repo/skype.flatpakref --user
Installing: com.skype.Client/x86_64/alpha
Installing: com.skype.Client/x86_64/alpha from com.skype.Client-3-origin
[####################] Downloading: 56.2 MB/56.2 MB (2.8 MB/s)     
error: Wrong size for extra data https://go.skype.com/skypeforlinux-64.deb
```

Sorry to bother, I guess Microsoft changed the RPM again. Of course making a versioned package was too hard. Maybe you could fetch them from https://repo.skype.com/deb/pool/main/s/skypeforlinux/ instead? Those have the version in the filename.

**Comment by alexlarsson** [comment]
Skype is now on flathub. See https://flathub.org/ for the details.

**Comment by enricotagliavini** [comment]
Uh sorry I missed it. Thank you :)
