### ISSUE TITLE
Error when running app

### ISSUE THREAD

**Issue by sebix** [alexlarsson/skype-app#8]
Hi,

I installed (I hope it's correct? Its not well documented) this app this way, but it fails to run 
```bash
> flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
> flatpak install gnome org.freedesktop.Platform//1.4
> flatpak install --from https://s3.amazonaws.com/alexlarsson/skype-repo/skype.flatpakref
> flatpak run com.skype.Client
Gtk-Message: Failed to load module "canberra-gtk-module"
No protocol specified
```
On the host canberra is installed.

**Comment by alexlarsson** [comment]
I get that warning too, it doesn't really matter. I wonder why its not working for you though.

@snaggen any idea?

**Comment by snaggen** [comment]
Gtk2 is built and provided with the flatpak app, so maybe there is some dependency missing...

**Comment by alexlarsson** [comment]
Seems to be an X issue:
http://unix.stackexchange.com/questions/85782/error-no-protocol-specified-when-running-from-remote-machine-via-ssh

Can you try `xhost +`

**Comment by sebix** [comment]
The window opens and after the progress symbol disappears the content of the window turns white and I get this output on the terminal:

> A Parser-blocking, cross-origin script, https://auth.gfx.ms/16.000.26940.00/DefaultLoginPaginatedStrings.EN.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://auth.gfx.ms/16.000.26940.00/DefaultLoginPaginatedStrings.EN.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.
A Parser-blocking, cross-origin script, https://auth.gfx.ms/16.000.26940.00/DefaultLogin_PCore.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

I have the menu bar, but I can't login etc.
